GET http://localhost:4000/todo

###

POST http://localhost:4000/todo
Content-Type: application/json

{
    "title":"Title 2",
    "description":"Description 2"
}

###

GET http://localhost:4000/todo/6324


###

PUT http://localhost:4000/todo/6324
Content-Type: application/json

{
    "title":"Updated Title 2",
    "description":"Updated Description 2"
}


###
DELETE  http://localhost:4000/todo/6324


###

POST http://localhost:4000/users
Content-Type:  application/json

{
   "name":"Mary Mwangi" ,
   "email":"mary3@gmail.com",
   "password":"12345678"
}


###

GET http://localhost:4000/users


###
GET http://localhost:4000/users?email='joy@gmail.com'


###
GET http://localhost:4000/users/user/f8249d87-9637-4c20-a5a5-1cc7073aa79a

###

PUT http://localhost:4000/users/f8249d87-9637-4c20-a5a5-1cc7073aa79a
Content-Type:  application/json

{
   "name":"Joy Mary Jepkosgei" ,
   "email":"joymary@gmail.com",
   "password":"123456789"
}


###

DELETE http://localhost:4000/users/cd5e45bd-92c0-4c36-a907-5f79fe28d4d8


########

POST http://localhost:4000/landlords
Content-Type:  application/json

{
    "name":"Belinda Florence",
    "email":"belinda1@gmail.com",
    "propertyDocs":"link",
    "password":"Test@2023"

}

###

POST http://localhost:4000/landlords/login
Content-Type:  application/json

{
  
    "email":"belinda1@gmail.com",
    "password":"Test@2023"

}
###
GET http://localhost:4000/landlords/approved
###
GET http://localhost:4000/landlords/unapproved
###

GET http://localhost:4000/landlords/get/30d2b669-adc5-478b-b01e-3b72a569a4cb

###
PUT http://localhost:4000/landlords/30d2b669-adc5-478b-b01e-3b72a569a4cb
Content-Type: application/json

{
  "name":"Allan Kamau",
  "email":"allan23@gmail.com"
}


####
POST http://localhost:4000/landlords/login
Content-Type: application/json

{
 "email":"jonathan@gmail.com",
 "password":"12345678"
}
###
DELETE  http://localhost:4000/landlords/30d2b669-adc5-478b-b01e-3b72a569a4cb
###
PUT http://localhost:4000/admin/dc95e911-3818-4158-a27a-00a9de99bdc8


###

POST http://localhost:4000/property
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRjOTVlOTExLTM4MTgtNDE1OC1hMjdhLTAwYTlkZTk5YmRjOCIsIm5hbWUiOiJCZWxpbmRhIEZsb3JlbmNlIiwiZW1haWwiOiJiZWxpbmRhMUBnbWFpbC5jb20iLCJpYXQiOjE2ODM3MDU0NTAsImV4cCI6MTY4NDA2NTQ1MH0.wrcxQYnDUmiy7yvVQsQELkN7zvISDih20plLSSap1eU

  {
       "name":"House of Jitu",
        "location":"Nyeri",
        "lat":"32.05",
        "lon":"-0.32",
        "images":"link",
        "videos":"link",
        "price":20000,
        "condition":"Good Condition"
  }

###
  # dc95e911-3818-4158-a27a-00a9de99bdc8
GET http://localhost:4000/property


###

GET http://localhost:4000/property/c7a29a9d-a14c-4418-85c5-d9d037540363

###
PUT http://localhost:4000/property/c7a29a9d-a14c-4418-85c5-d9d037540363
Content-Type: application/json

  {
       "name":"House of Full-stacks",
        "location":"Nyeri",
        "lat":"32.05",
        "lon":"-0.32",
        "images":"link",
        "videos":"link",
        "price":20000,
        "condition":"Good Condition",
        "owner":"30d2b669-adc5-478b-b01e-3b72a569a4cb"
  }

####
DELETE  http://localhost:4000/property/c7a29a9d-a14c-4418-85c5-d9d037540363