GET http://localhost:4000/todo

###

POST http://localhost:4000/todo
Content-Type: application/json

{
    "title":"Title 2",
    "description":"Description 2"
}

###

GET http://localhost:4000/todo/6324


###

PUT http://localhost:4000/todo/6324
Content-Type: application/json

{
    "title":"Updated Title 2",
    "description":"Updated Description 2"
}


###
DELETE  http://localhost:4000/todo/6324


###

POST http://localhost:4000/users
Content-Type:  application/json

{
   "name":"Admin" ,
   "email":"admin@gmail.com",
   "password":"Amazing@2024"
}
####
POST http://localhost:4000/users/login
Content-Type:  application/json

{
     "email":"kev@gmail.com",
   "password":"12345678"
}

###
POST http://localhost:4000/users/login
Content-Type:  application/json

{
   "email":"esther@gmail.com",
   "password":"12345678"
}


###

GET http://localhost:4000/users


###
GET http://localhost:4000/users/one?email='kelvin1@gmail.com'


###
GET http://localhost:4000/users/user/7f643dd9-18c7-4797-ba1e-471802e05f4e

###

PUT http://localhost:4000/users/fsdsd
Content-Type:  application/json

{
   "name":"Joy Mary Jepkosgei" ,
   "email":"joymary@gmail.com",
   "password":"123456789"
}


###

DELETE http://localhost:4000/users/cb7a5b45-d203-4f85-99be-b793702a9e8e


########

POST http://localhost:4000/landlords
Content-Type:  application/json

{
    "name":"John Doe",
    "email":"jndambukitest@gmail.com",
    "propertyDocs":"link",
    "password":"Test@2023"

}

###

POST http://localhost:4000/landlords/login
Content-Type:  application/json

{
  
    "email":"jndambukitest@gmail.com",
    "password":"Test@2023"

}
###
GET http://localhost:4000/landlords/approved
###
GET http://localhost:4000/landlords/unapproved
###

GET http://localhost:4000/landlords/get/30d2b669-adc5-478b-b01e-3b72a569a4cb

####
GET http://localhost:4000/landlords/get?email='jonathan@gmail.com'
###
PUT http://localhost:4000/landlords/30d2b669-adc5-478b-b01e-3b72a569a4cb
Content-Type: application/json

{
  "name":"Allan Kamau",
  "email":"allan23@gmail.com"
}


####
POST http://localhost:4000/landlords/login
Content-Type: application/json

{
 "email":"jonathan@gmail.com",
 "password":"12345678"
}
###


####
DELETE  http://localhost:4000/landlords/30d2b669-adc5-478b-b01e-3b72a569a4cb
###
POST http://localhost:4000/users/login
Content-Type: application/json

{
   "email":"admin@gmail.com",
   "password":"Amazing@2024"
}
####
PUT http://localhost:4000/admin/35e0a3a1-f1a7-4ba9-9365-866228f3339e
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzZmM5Y2Q4LTk2YTItNDBhYy1hOWIzLWM5ZWI5ZGVjMzg1YSIsIm5hbWUiOiJKYXkgIiwiZW1haWwiOiJqYXlAZ21haWwuY29tIiwicm9sZXMiOiJhZG1pbiIsImlhdCI6MTY4Mzc5MDE2Nn0.7SYfWt0yv6NHuSCbDpipmcELiwHUIC-tVf-OR391hsU

###

POST http://localhost:4000/property
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1ZTBhM2ExLWYxYTctNGJhOS05MzY1LTg2NjIyOGYzMzM5ZSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam5kYW1idWtpdGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2ODM3OTc5MDcsImV4cCI6MTY4NDE1NzkwN30.hUS5mpfgMaBvUehVSOBbzT4lVtXysoiOl6zW5L8n9bw

  {
       "name":"White House ",
        "location":"Nyeri",
        "lat":"32.05",
        "lon":"-0.32",
        "images":"link",
        "videos":"link",
        "price":20000,
        "condition":"Good Condition"
  }

###
  # dc95e911-3818-4158-a27a-00a9de99bdc8
GET http://localhost:4000/property


###

GET http://localhost:4000/property/8323e09c-70ef-4566-bf83-59e5ce0f9be5

###
PUT http://localhost:4000/property/8323e09c-70ef-4566-bf83-59e5ce0f9be5
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1ZTBhM2ExLWYxYTctNGJhOS05MzY1LTg2NjIyOGYzMzM5ZSIsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam5kYW1idWtpdGVzdEBnbWFpbC5jb20iLCJpYXQiOjE2ODM3OTc5MDcsImV4cCI6MTY4NDE1NzkwN30.hUS5mpfgMaBvUehVSOBbzT4lVtXysoiOl6zW5L8n9bw

  {
       "name":"State House",
        "location":"Nyeri",
        "lat":"32.05",
        "lon":"-0.32",
        "images":"link",
        "videos":"link",
        "price":20000,
        "condition":"Good Condition"

  }

####
DELETE  http://localhost:4000/property/8323e09c-70ef-4566-bf83-59e5ce0f9be5